name: mediassist
description: "A comprehensive health reminder application."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  # State Management & Utilities
  get: ^4.7.3
  get_storage: ^2.1.1
  intl: ^0.20.2

  # Notifications & Alarms
  flutter_local_notifications: ^21.0.0
  flutter_foreground_task: ^9.2.2
  alarm: ^5.2.1
  uuid: ^4.5.1

  # Permissions
  permission_handler: ^12.0.1
  battery_optimization_helper: ^0.2.0
  open_settings: ^2.0.0
  app_settings: ^5.1.1

  # UI
  flutter_slidable: ^4.0.3
 

  # Icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/